version: "3"

networks:
  loki:

volumes:
  prom_data:

x-logging: &logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}"
    max-size: 10M
    max-file: 2

services:
  python_app:
    image: evermake/devops-simple-app:latest
    ports:
      - 8000:8000
    logging: *logging
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

  loki:
    platform: linux/arm64
    image: grafana/loki:2.9.2
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    logging: *logging
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    ports:
      - 9000:9000
    logging: *logging
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - 9090:9090
    logging: *logging
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      restart: unless-stopped
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - ./grafana:/etc/grafana/provisioning/datasources
      ports:
        - 3000:3000
      logging: *logging
      networks:
        - loki
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 1024M
