name: Snyk (Python)

on:
  push:
    paths:
      - app_python/**
  pull_request:
    paths:
      - app_python/**

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
